name: 4mood
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./internal/database:/root/internal/database
      - ./.env:/root/.env
      - ./localhost.crt:/root/localhost.crt
      - ./localhost.key:/root/localhost.key
    environment:
      - DATABASE_URL=sqlite:///root/internal/database/database.db